# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 10:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('username', models.CharField(
                    blank=True,
                    max_length=60,
                    null=True)),
                ('email', models.CharField(
                    blank=True,
                    max_length=60,
                    null=True)),
                ('phone', models.CharField(
                    blank=True,
                    max_length=15,
                    null=True,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Format '+999999999'.Upto 15 digits.",
                            regex='^\\+?1?\\d{9,15}$')
                    ]
                )),
                ('department', models.CharField(blank=True, choices=[
                    ('CSE', 'Computer Science and Engineering'),
                    ('IT', 'Information Technology'),
                    ('EE', 'Electrical Engineering'),
                    ('ECE', 'Electronics and Communication Engineering'),
                    ('EEE', 'Electrical and Electronics Engineering'),
                    ('CE', 'Civil Engineering'),
                    ('IC', 'Instrumentation and Control Engineering'),
                    ('ME', 'Mechanical Engineering')],
                    max_length=15,
                    null=True)),
                ('designation', models.CharField(
                    blank=True, max_length=60, null=True)),
                ('created', models.DateTimeField(
                    auto_now_add=True, null=True, verbose_name='Created')),
                ('group', models.ForeignKey(
                    default=1,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('username',
                 models.CharField(blank=True,
                                  max_length=60,
                                  null=True)),
                ('Branch', models.CharField(
                    blank=True,
                    choices=[
                        ('CSE', 'Computer Science and Engineering'),
                        ('IT', 'Information Technology'),
                        ('EE', 'Electrical Engineering'),
                        ('ECE', 'Electronics and Communication Engineering'),
                        ('EEE', 'Electrical and Electronics Engineering'),
                        ('CE', 'Civil Engineering'),
                        ('IC', 'Instrumentation and Control Engineering'),
                        ('ME', 'Mechanical Engineering')],
                    max_length=5, null=True)),
                ('email', models.CharField(
                    blank=True,
                    max_length=60,
                    null=True)),
                ('phone', models.CharField(
                    blank=True,
                    max_length=15,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Format '+999999999'.Upto 15 digits.",
                            regex='^\\+?1?\\d{9,15}$')
                    ])),
                ('created', models.DateTimeField(
                    auto_now_add=True,
                    null=True, verbose_name='Created')),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='auth.Group')),
            ],
        ),
    ]
