# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 10:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(
                    blank=True, max_length=60, null=True)),
                ('group', models.CharField(
                    blank=True, max_length=60, null=True)),
                ('email', models.CharField(
                    blank=True, max_length=60, null=True)),
                ('phone', models.CharField(
                    blank=True, max_length=15, validators=[django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(
                    blank=True, max_length=15, null=True)),
                ('designation', models.CharField(
                    blank=True, max_length=60, null=True)),
                ('created', models.DateTimeField(
                    auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Branch',
            field=models.CharField(
                blank=True, choices=[
                    ('CSE', 'Computer Science and Engineering'),
                    ('IT', 'Information Technology'),
                    ('EE', 'Electrical Engineering'),
                    ('ECE', 'Electronics and Communication Engineering'),
                    ('EEE', 'Electrical and Electronics Engineering'),
                    ('CE', 'Civil Engineering'),
                    ('IC', 'Instrumentation and Control Engineering'),
                    ('ME', 'Mechanical Engineering')], max_length=5, null=True),
        ),
    ]
