# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180818_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('ECE', 'Electronics and Communication Engineering'), (
                'EEE', 'Electrical and Electronics Engineering'), ('CE', 'Civil Engineering'), ('IC', 'Instrumentation and Control Engineering'), ('ME', 'Mechanical Engineering')], max_length=15, null=True),
        ),
    ]
