# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180821_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='group',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
