# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count_division',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'DividedCount',
            },
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[
                    ('CSE', 'Computer Science and Engineering'),
                    ('IT', 'Information Technology'),
                    ('EE', 'Electrical Engineering'),
                    ('ECE', 'Electronics and Communication Engineering'),
                    ('EEE', 'Electrical and Electronics Engineering'),
                    ('CE', 'Civil Engineering'),
                    ('IC', 'Instrumentation and Control Engineering'),
                    ('ME', 'Mechanical Engineering')], max_length=10)),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_total_count', models.IntegerField(default=0)),
                ('item_department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='inventory.departments')),
            ],
        ),
        migrations.CreateModel(
            name='storage_locations',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='inventory.departments')),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.AddField(
            model_name='count_division',
            name='item_name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='count_division',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='inventory.storage_locations'),
        ),
    ]
