# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department',
            field=models.CharField(choices=[(
                'CSE', 'Computer Science and Engineering'),
                ('IT', 'Information Technology'),
                ('EE', 'Electrical Engineering'),
                ('ECE', 'Electronics and Communication Engineering'),
                ('EEE', 'Electrical and Electronics Engineering'),
                ('CE', 'Civil Engineering'),
                ('IC', 'Instrumentation and Control Engineering'),
                ('ME', 'Mechanical Engineering')], max_length=10),
        ),
    ]
