# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180820_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage_locations',
            options={'verbose_name': 'Location'},
        ),
    ]
